name: Linux (with GCC)

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    timeout-minutes: 15

    container:
      image: ghcr.io/mattkretz/cplusplus-ci/gcc15

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          add-apt-repository ppa:ubuntu-toolchain-r/test
          add-apt-repository ppa:texus/raylib
          apt-get update
          apt-get install -y libraylib5-dev libbox2d-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev
      - name: Configure CMake
        run: |
          mkdir topdown/build 
          cd topdown/build 
          cmake -DCMAKE_BUILD_TYPE=Debug ..
      - name: Build executable
        working-directory: ./topdown/build
        run: make
